Fixed sign in and sign out buttons CSS
andrayantelo/calendar-reboot pull request #106
Opened 2017-01-23 21:43 UTC by andrayantelo

Also, made the sign in function use sign in with redirect instead of with a popup.

2017-01-23 22:02 UTC, johntyree requested changes

2017-01-23 22:02 UTC, johntyree commented on .firebaserc
> +}
File should end with a newline.

2017-01-23 22:02 UTC, johntyree commented on database.rules.json
> +    ".read": "auth != null",
This is OK for now. You'll want to further limit this later so that users can only read / write their own data.

2017-01-23 22:02 UTC, johntyree commented on public/calendar.css
> +  display: flex;
My understanding is that this isn't cross platform yet and that you have to use the -moz and -webkit versions in addition to this. Maybe look into that?

2017-01-23 22:02 UTC, johntyree commented on .firebaserc
> +}
missing newline

2017-01-23 22:02 UTC, johntyree commented on database.rules.json
> +    ".read": "auth != null",
You'll want to limit this such that users can only read/write their own data eventually. (open an issue?)

2017-01-23 23:00 UTC, johntyree requested changes

2017-01-23 23:00 UTC, johntyree commented on public/calendar_reboot.js
> +       }.bind(this));
There is whitespace (ws) at the end of this line

2017-01-23 23:00 UTC, johntyree commented on public/calendar_reboot.js
> +        this.store.user = null;
What about the active calendar and the list of calendars in the drop down?

2017-01-23 23:00 UTC, johntyree commented on public/index.html
> +                <button class="btn btn-primary navbar-btn " hidden id="sign-out"><!-- mdl-js-button mdl-js-ripple-effect mdl-color-text--white"-->
What is commented out here? Should it be uncommented or should it be removed?

2017-01-23 23:06 UTC, andrayantelo commented on public/index.html
> +                <button class="btn btn-primary navbar-btn " hidden id="sign-out"><!-- mdl-js-button mdl-js-ripple-effect mdl-color-text--white"-->
Should be removed.

2017-01-23 23:11 UTC, andrayantelo commented on database.rules.json
> +    ".read": "auth != null",
Opened issue #107

2017-01-23 23:15 UTC, johntyree requested changes

2017-01-23 23:15 UTC, johntyree commented on public/calendar_reboot.js
> +        this.store.user = null;
If the user has signed out, they should no longer be available.

2017-01-23 23:54 UTC, johntyree commented on public/index.html
> +                <button class="btn btn-primary navbar-btn " hidden id="sign-in">
Why does the sign-in button start out hidden?

2017-01-23 23:56 UTC, johntyree commented on public/index.html
> +                <button class="btn btn-primary navbar-btn " hidden id="sign-in">
Apparently, `firebase.auth` always chooses one of the two buttons to unhide.

What about the other buttons?

2017-01-24 00:01 UTC, johntyree approved these changes

2017-01-24 00:06 UTC, merged