Update sample_calendar.json
andrayantelo/calendar-reboot pull request #116
Opened 2017-01-31 19:20 UTC by andrayantelo

Is this a good way to structure it to manage authorization for reading and writing to different calendars?

2017-01-31 19:44 UTC, andrayantelo commented on sample_calendar.json
> +            "permissionWrite": "JULxYGaHuFYlSkXqTC2Fx9KIofp2"
I could also do:
"permissionRead" : {
    "JULxYGaHuFYlSkXqTC2Fx9KIofp2" : "true"
}

Although, I'm not sure if that would make sense? I mean, will it ever be false?

2017-02-04 04:38 UTC, johntyree requested changes

2017-02-04 04:38 UTC, johntyree commented on database.rules.json
> +          ".read" : "auth!== null && data.parent().child('read').hasChild(auth.uid) && data.parent().child('read').child(auth.uid).val() === true",
Two things here.

First, you shouldn't ever need to do `=== true`. Think about why.

Second, I think the value of the key doesn't really matter anyway. You're not going to put in uids with values that are anything other than `true` right? What about `".read": "auth !== null && data.parent().child('read/' + auth.uid).exists()"` ?

2017-02-04 20:48 UTC, johntyree requested changes
https://jsonformatter.curiousconcept.com/

2017-02-04 20:48 UTC, johntyree commented on database.rules.json
> +        }
Missing a comma

2017-02-04 20:48 UTC, johntyree commented on database.rules.json
> +          ".read" : "auth!== null && data.parent().child('read/' + auth.uid).exists()",
Missing a space after first `auth`

2017-02-04 21:03 UTC, johntyree approved these changes

2017-02-04 21:03 UTC, merged