Refactoring the code for the local Storage manager
andrayantelo/calendar-reboot pull request #131
Opened 2017-02-07 19:29 UTC by andrayantelo

Getting rid of the localStorage helper functions in checkit.js. Moving a few to localStorage manager object.

2017-02-07 20:56 UTC, johntyree requested changes

2017-02-07 20:56 UTC, johntyree commented on docs/store.js
> +            storageItem = JSON.parse(storagItem);
Typo

2017-02-07 20:56 UTC, johntyree commented on docs/store.js
> +    self.setInStorage = function(key, val) {
These functions shouldn't be on self. No one outside storage should use them

2017-02-07 21:36 UTC, andrayantelo commented on docs/store.js
> +            storageItem = JSON.parse(storagItem);
Fixed

2017-02-07 21:36 UTC, andrayantelo commented on docs/store.js
> +    self.setInStorage = function(key, val) {
Fixed

2017-02-08 07:37 UTC, johntyree approved these changes

2017-02-08 18:58 UTC, merged