Validate data
andrayantelo/calendar-reboot pull request #133
Opened 2017-02-07 23:11 UTC by andrayantelo

Working on validation rules as well as fixing read and write rules.

2017-02-08 07:44 UTC, johntyree commented on docs/store.js
> +        // has permission to write into calendars/calUniqueId
Maybe you should be allowed to create a new calendar as long as the final state is that the calendar is also in your users list of cal ids?

2017-02-10 05:01 UTC, johntyree commented on docs/store.js
> +        updates['calendars/' + calUniqueId + '/calendarState'] = calState;
Not important, but you can also just define all these when you define the object literal. Not necessarily better or worse.

```
var updates = {
  'users/' + userId + '/allCalendarIds/' + calUniqueId: calTitle,
 ....
}
```

2017-02-11 18:26 UTC, andrayantelo commented on docs/store.js
> +        updates['calendars/' + calUniqueId + '/calendarState'] = calState;
Oh okay. Will keep that in mind.

2017-02-12 01:21 UTC, johntyree requested changes

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +          //".write" : "true",
Remove this

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +            ".write" : "auth !== null && auth.uid === $uid && (!data.exists() || root.child('calendars/' + newData.val() + '/writers/' + auth.uid).exists())",
Really you only need to be able to read the calendar to show it.

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +            ".write" : "auth !== null && auth.uid === $uid && (!data.exists() || root.child('calendars/' + newData.val() + '/writers/' + auth.uid).exists())",
Not important now, but if it's supposed to be possible to share a calendar somehow then we'll have to look at this again

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +            ".validate" : "newData.isString() && newData.val().length > 0 && newData.val().matches(/\\d{8}/)"
I think the regex alone is enough here. If it's not a string it will fail. If it is, then the length will be restricted to exactly 8.

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +            ".validate" : "newData.isString() && newData.val().length > 0"
Probably something like `newData.val().matches(/([A-Za-z0-9]+/)` is better here. The id should be just be some blob of alphanumeric something or another.

2017-02-12 01:21 UTC, johntyree commented on database.rules.json
> +          ".write" : "auth !== null && (!data.exists() || root.child('calendars/' + $calendarId + '/writers/' + auth.uid).exists())",
You're already here.  `data.child(auth.uid).exists()` ?  Maybe `data.parent.child` at worst.

2017-02-12 01:21 UTC, johntyree commented on docs/store.js
> +        .then(function() {
fix the indentation here please

2017-02-12 01:21 UTC, johntyree commented on docs/store.js
> +        .then(function() {
indentation on all of these.

2017-02-12 01:21 UTC, johntyree commented on docs/store.js
> +        // TODO work on save method, how to save readers, writers, permissions,
Is this out of date now?

2017-02-12 01:21 UTC, johntyree commented on docs/store.js
> +            self.endWork();
You're not done with work until those other promises return.  You need a `Promise.all` here.

2017-02-12 20:08 UTC, andrayantelo commented on database.rules.json
> +          //".write" : "true",
Done.

2017-02-12 20:08 UTC, andrayantelo commented on database.rules.json
> +            ".write" : "auth !== null && auth.uid === $uid && (!data.exists() || root.child('calendars/' + newData.val() + '/writers/' + auth.uid).exists())",
Okay.

2017-02-12 20:09 UTC, andrayantelo commented on database.rules.json
> +            ".write" : "auth !== null && auth.uid === $uid && (!data.exists() || root.child('calendars/' + newData.val() + '/writers/' + auth.uid).exists())",
Changed it to readers.

2017-02-12 20:09 UTC, andrayantelo commented on database.rules.json
> +            ".validate" : "newData.isString() && newData.val().length > 0 && newData.val().matches(/\\d{8}/)"
Left just the regex.

2017-02-12 20:09 UTC, andrayantelo commented on database.rules.json
> +            ".validate" : "newData.isString() && newData.val().length > 0"
Used that as uniqueId's validation rule.

2017-02-12 20:09 UTC, andrayantelo commented on database.rules.json
> +          ".write" : "auth !== null && (!data.exists() || root.child('calendars/' + $calendarId + '/writers/' + auth.uid).exists())",
Changed it to the first option.

2017-02-12 20:09 UTC, andrayantelo commented on docs/store.js
> +        .then(function() {
Fixed.

2017-02-12 20:09 UTC, andrayantelo commented on docs/store.js
> +        .then(function() {
Fixed.

2017-02-12 20:09 UTC, andrayantelo commented on docs/store.js
> +        // TODO work on save method, how to save readers, writers, permissions,
Yes. Removed.

2017-02-12 20:09 UTC, andrayantelo commented on docs/store.js
> +            self.endWork();
Done.

2017-02-14 04:45 UTC, johntyree requested changes
This is probably good to go. I only had some cosmetic suggestions.

2017-02-14 04:45 UTC, johntyree commented on docs/store.js
> +                console.error('Unable to remove calendar from user\'s allCalendarIds: ' + err);
It's usually easier to read if you make use of the other type of quotes so that you don't have to escape.

2017-02-14 04:45 UTC, johntyree commented on docs/store.js
> +                .then(function() {
I find that lining up the methods vertically if they are going to operate on the same object is an easy way to organize it.
```
Promise.all([...])
       .then(function() {
          ...
       })
       .catch(function() {});
```
However you decide to organize it, it should be such that lines that begin in the column indicate new *statements*, not expressions. If an expression continues onto a second line, it should be indented somehow to give a visual indication that this is all a single computation that will return a single value.

2017-02-14 17:31 UTC, andrayantelo commented on docs/store.js
> +                console.error('Unable to remove calendar from user\'s allCalendarIds: ' + err);
Do you mean back ticks?

2017-02-14 17:36 UTC, merged