Remove empty weeks function is now checkit method.
andrayantelo/calendar-reboot pull request #154
Opened 2017-02-25 20:51 UTC by andrayantelo

2017-02-25 20:56 UTC, johntyree requested changes

2017-02-25 20:56 UTC, johntyree commented on docs/checkit.js
> +            if ($(this).children().hasClass("nill"))
Not that it matters, but "nill" is usually spelled "nil."

2017-02-25 20:56 UTC, johntyree commented on docs/checkit.js
> +CheckIt.prototype.removeEmptyWeeks = function(calObj, $div) {
`$div` could have a more descriptive name. This function can't take just any div. It has to be a `$calendarDiv` that contains `.month` and `.week` etc.

2017-02-25 20:56 UTC, johntyree commented on docs/checkit.js
> +    })
This is a clever way to figure out if the week should be removed or not, but you can also just ask jquery how many things have the `nil` class.

Try something like `$(this).children('.nil').length`

2017-02-25 20:58 UTC, andrayantelo commented on docs/checkit.js
> +            if ($(this).children().hasClass("nill"))
Gosh darn it. It matters to me.

2017-02-25 21:03 UTC, andrayantelo commented on docs/checkit.js
> +CheckIt.prototype.removeEmptyWeeks = function(calObj, $div) {
Changed name to $calendarDiv

2017-02-26 19:15 UTC, johntyree requested changes

2017-02-26 19:15 UTC, johntyree commented on docs/checkit.js
> +    $calendarDiv.find('.month').find('.week').each( function(index) {
These are CSS selectors, right? I don't think you should have to do multiple calls in a row. `find('.month > .week')`

2017-02-26 19:15 UTC, johntyree commented on docs/checkit.js
> +        if ($(this).find('td').children('.nil').length === 7) {
`.find("td > .nil")`

2017-02-26 19:18 UTC, johntyree approved these changes

2017-02-26 20:17 UTC, merged