Fixed selector syntax
andrayantelo/calendar-reboot pull request #156
Opened 2017-02-27 22:18 UTC by andrayantelo

2017-03-02 16:43 UTC, johntyree requested changes

2017-03-02 16:43 UTC, johntyree commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
Just use `'.month .week'` probably. You don't want this to break just because you change how the calendar part is structured in html

2017-03-02 17:57 UTC, andrayantelo commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
> is for direct children. .week is not a direct child of .month

2017-03-02 17:58 UTC, andrayantelo commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
">" is for direct children.

2017-03-02 17:59 UTC, andrayantelo commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
Could give tbody a class?

2017-03-02 18:00 UTC, andrayantelo commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
.monthBody? Then it would be .month > .monthBody > .week

2017-03-02 18:04 UTC, andrayantelo commented on docs/checkit.js
> +    $calendarDiv.find('.month > tbody > .week').each( function(index) {
Okay, if I just leave it as '.month . week' it works. This is how you select a descendant. (not necessarily a direct child).

2017-03-05 00:12 UTC, johntyree approved these changes

2017-03-05 00:32 UTC, merged