[WIP] Writing tests for checkit object
andrayantelo/calendar-reboot pull request #166
Opened 2017-03-05 03:15 UTC by andrayantelo

2017-03-05 03:37 UTC, johntyree requested changes

2017-03-05 03:37 UTC, johntyree commented on tests/tests.js
> +        assert.equal(selectorName.selector, expected);
This is good to check, but it doesn't protect you against something changing on the page. For example, suppose you refactor how the calendar works and need to change your date form selectors. This test will still pass but the selector won't *work*.

Is there a good way to test that each of the selectors actually selects an element?

2017-03-05 19:43 UTC, johntyree requested changes

2017-03-05 19:43 UTC, johntyree commented on docs/checkit.js
> +        if (monthObj.monthIndex === 0 || monthObj.isFirst) {
Is `monthObj.isFirst` the same as `index === 0` ?

2017-03-05 19:43 UTC, johntyree commented on docs/checkit.js
> +        if (monthObj.monthIndex === 0 || monthObj.isFirst) {
Do you need it elsewhere?

2017-03-05 19:46 UTC, andrayantelo commented on docs/checkit.js
> +        if (monthObj.monthIndex === 0 || monthObj.isFirst) {
isFirst means it is the very first month in the calendar the user built. index === 0 means it is January, and January can appear multiple times in the calendar.

2017-03-05 22:51 UTC, johntyree requested changes

2017-03-05 22:51 UTC, johntyree commented on docs/checkit.js
> +    // Add a month to this calendar
This comment seems wrong

2017-03-05 22:51 UTC, johntyree commented on docs/checkit.js
> +        if (monthObj.monthIndex === 0 || monthObj.isFirst) {
`index`, not `monthObj.index`. `index` is coming from the `monthObjects.forEach` loop above.

2017-03-06 02:17 UTC, johntyree requested changes

2017-03-06 02:17 UTC, johntyree commented on docs/checkit.js
> +    this.$calendarDiv.find('.activeDay').each( function(index, activeDay) {
Try 
```
this.$calendarDiv.find('.activeDay')
                 .filter('#' + todayId)
                 .children('.cell')
                 .addClass('currentDay');
```

2017-03-06 02:17 UTC, johntyree commented on docs/store.js
> +        var key = id;
`var key = prefix ? prefix + "_" + id : id;`

2017-03-06 02:17 UTC, johntyree commented on tests/tests.js
> +    $calendarDiv.empty();
If you need to do this, then you probably should start a second test and give them better names.

2017-03-06 02:17 UTC, johntyree commented on tests/tests.js
> +    assert.equal(this.$calendarDiv.find('#20171').find('.hidden').length, 7);
If you use a better selector you only need one call to `find`.

2017-03-06 02:17 UTC, johntyree commented on tests/tests.js
> +    assert.equal(this.$calendarDiv.find('#20171').find('.hidden').length, 6);
Same here. One `find` call.

2017-03-06 02:17 UTC, johntyree commented on tests/tests.js
> +    this.checkit.findCurrentDay();
What does this function do? The name suggests that it's going to e.g. locate the dom element corresponding to today and return it or something.

When you write functions that are going to mutate state, it's important to make sure that it's obvious that that's what's happening.

2017-03-06 02:17 UTC, johntyree commented on tests/tests.js
> +    this.fixture = $('#qunit-fixture');
`$fixture`

2017-03-06 02:45 UTC, johntyree requested changes

2017-03-06 02:45 UTC, johntyree commented on tests/tests.js
> +    assert.notOk($calendarDiv.find('20172').find('#yearHeader').text(),
Combine the calls to `find`

2017-03-06 02:45 UTC, johntyree commented on tests/tests.js
> +        $div.find('#' + monthObj.monthId).find('.daynumber').each( function(index) {
Combine `find` calls

2017-03-06 02:45 UTC, johntyree commented on tests/tests.js
> +        $div.find('#' + monthObj.monthId).find('.checkmark').each(function (index) {
Also here

2017-03-06 02:45 UTC, johntyree commented on tests/tests.js
> +    assert.equal(this.$calendarDiv.find('#20171').find('.hidden').length, 7);
and here

2017-03-06 02:45 UTC, johntyree commented on tests/tests.js
> +    assert.equal(this.$calendarDiv.find('#20170214').find('.checkmark')
and here

2017-03-06 18:34 UTC, merged