Github fork me image included
andrayantelo/calendar-reboot pull request #185
Opened 2017-04-18 16:38 UTC by andrayantelo

Resized for mobile devices.

2017-04-19 16:48 UTC, johntyree requested changes

2017-04-19 16:48 UTC, johntyree commented on docs/calendar.css
> +  #forkMe {
Why is this repeated?

2017-04-19 19:03 UTC, andrayantelo commented on docs/calendar.css
> +  #forkMe {
It gets resized for tablet and larger screen sizes.

2017-04-20 00:05 UTC, johntyree commented on docs/calendar.css
> +  #forkMe {
Oh I see. The diff on GitHub obscures the fact that this is inside of a `@media` query.

2017-04-20 00:05 UTC, johntyree approved these changes

2017-04-20 16:15 UTC, merged